import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import FadeIn from "./components/FadeIn";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Theo Poette - Homepage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-80 bg-gray-400">
        {/* placeholder for now */}
        test
      </div>

      <FadeIn>
        <div className="mt-8 flex w-full items-center justify-center rounded-lg bg-blue-200/70 px-8 py-4">
          <p className="text-white opacity-100">
            Hello, I'm Theo Poette, a full-stack software engineer based in
            France 🇫🇷 !
          </p>
        </div>

        <div className="mt-8 flex w-full items-center justify-between">
          <div>
            <p className="text-3xl font-semibold tracking-wide text-white">
              Theo Poette
            </p>
            <p className="text-lg font-light tracking-wide text-white">
              Full-stack software engineer
            </p>
          </div>
          <Image
            className="h-32 w-32 overflow-hidden rounded-full"
            src="/me.jpg"
            alt="Picture of the author"
            width={400}
            height={400}
          />
        </div>
      </FadeIn>
    </>
  );
};

export default Home;
